### ISSUE TITLE
What is the structure of output camera covariance?

### ISSUE THREAD

**Issue by melhashash** [michalpolic/usfm.github.io#4]
Hi, thanks for making the code available.

I am testing the code and I would like to understand the structure of the camera covariance matrix in the output txt file.

suppose 10 images (6 parameters each) with 10 camera pinhole models (4 parameters each), how to get the sub covariance matrix for each? is it the extrinsics first then intrinsics or extrinsics+intrinsics for each camera together?

Also, I found that the dimension of the covariance matrix is larger than the # of total parameters by 7. So for the above example, the output is `107 x 107`, could you explain?

Thanks

**Comment by michalpolic** [comment]
Hello Mostafa, thank you for the question. I would guess that this is the inversion of extended information matrix about its nullspace. There are 7 DoF as the whole scene can be shifted, scaled and rotated without change of the reprojection error. Therefore you cannot directly compute the inversion of information matrix because of its lower rank. The MP-inversion does fix scale, shift and rotation an exact way and we can do the same by extending the information matrix abut its nullspace. After this extension, we have full rank matrix and the computation of covariance matrix is much more stable and faster. Please see the details in paper [https://openaccess.thecvf.com/content_ECCV_2018/papers/Michal_Polic_Fast_and_Precise_ECCV_2018_paper.pdf](https://openaccess.thecvf.com/content_ECCV_2018/papers/Michal_Polic_Fast_and_Precise_ECCV_2018_paper.pdf) . I have not used the code for some time, so, I don't remember details of the implementation. But, we can plan a call and look at it together. My email is policmic(at)fel.cvut.cz .

**Comment by melhashash** [comment]
Thanks for your response.
